# Generated by Django 5.1.3 on 2024-12-01 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('space', models.IntegerField(verbose_name='Площадь')),
                ('count_room', models.IntegerField(verbose_name='Кол-во комнат')),
                ('amenities', models.JSONField(default=list, verbose_name='Удобства')),
                ('img1', models.ImageField(upload_to='', verbose_name='Изображение 1')),
                ('img2', models.ImageField(upload_to='', verbose_name='Изображение 2')),
                ('img3', models.ImageField(upload_to='', verbose_name='Изображение 3')),
                ('img4', models.ImageField(upload_to='', verbose_name='Изображение 4')),
            ],
            options={
                'verbose_name': 'Категория комнаты',
                'verbose_name_plural': 'Категории комнат',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер комнаты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoryroom')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('mail', models.CharField(max_length=100, verbose_name='Почта')),
                ('total_price', models.IntegerField(verbose_name='Итоговая цена')),
                ('check_in_date', models.DateField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateField(verbose_name='Дата выезда')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
