# Generated by Django 5.1.3 on 2024-11-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('space', models.IntegerField(verbose_name='Площадь')),
                ('count_room', models.IntegerField(verbose_name='Кол-во комнат')),
                ('amenities', models.JSONField(default=list, verbose_name='Удобства')),
            ],
        ),
    ]
