# Generated by Django 5.1.3 on 2024-12-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=4000, verbose_name='Цена комнаты'),
            preserve_default=False,
        ),
    ]
